# Generated by Django 6.0.6 on 2026-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=20)),
                ('innhold', models.TextField()),
                ('status', models.CharField(default='ny', max_length=10)),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
