# Generated by Django 6.0.6 on 2026-06-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostIT',
        ),
    ]
